import type { CSSProperties } from 'react'

export const editableRootStyle = {
  // Snaxxco reference palette: warm cream page, loud tomato-red display/action,
  // orange/yellow highlights, cocoa text, and candy-colored support panels.
  '--slot4-page-bg': '#f7f7ee',
  '--slot4-page-text': '#201916',
  '--slot4-panel-bg': '#fff',
  '--slot4-surface-bg': '#fefee8',
  '--slot4-raised-bg': '#fff',
  '--slot4-muted-text': '#6b5843',
  '--slot4-soft-muted-text': '#a4aeb5',
  '--slot4-accent': '#ff0300',
  '--slot4-accent-fill': '#ff0300',
  '--slot4-accent-soft': '#ffe3e1',
  '--slot4-on-accent': '#fff',
  '--slot4-dark-bg': '#201916',
  '--slot4-dark-text': '#fff',
  '--slot4-media-bg': '#f4dab5',
  '--slot4-cream': '#fefee8',
  '--slot4-warm': '#ffef14',
  '--slot4-lavender': '#9adbff',
  '--slot4-gray': '#edeef2',
  '--slot4-green': '#aeff8c',
  '--slot4-pink': '#f54f95',
  '--slot4-orange': '#ff8f00',
  '--slot4-body-gradient': 'none',
  '--editable-page-bg': '#f7f7ee',
  '--editable-page-text': '#201916',
  '--editable-container': '1320px',
  '--editable-border': '#201f1f12',
  '--editable-border-subtle': '#201f1f0a',
  '--editable-nav-bg': '#f7f7ee',
  '--editable-nav-text': '#ff0300',
  '--editable-nav-active': '#ff0300',
  '--editable-nav-active-text': '#fff',
  '--editable-cta-bg': '#ff0300',
  '--editable-cta-text': '#fff',
  '--editable-search-bg': '#fff',
  '--editable-footer-bg': '#ff0300',
  '--editable-footer-text': '#fff',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-[#201916]/15',
  shadow: 'shadow-[0_12px_0_rgba(32,25,22,0.08)]',
  shadowStrong: 'shadow-[0_24px_60px_rgba(32,25,22,0.18)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(0,0,0,0.02),rgba(0,0,0,0.72))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8',
    sectionY: 'py-20 sm:py-24 lg:py-32',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[140px] shrink-0 snap-start sm:w-[160px]',
  },
  type: {
    eyebrow: 'text-xs font-black uppercase tracking-[0.18em] text-[var(--slot4-accent)]',
    heroTitle: 'text-6xl font-black uppercase leading-[.82] tracking-normal sm:text-7xl lg:text-8xl',
    sectionTitle: 'text-4xl font-black uppercase leading-[.86] tracking-normal sm:text-6xl',
    body: 'text-base leading-relaxed',
  },
  surface: {
    card: `rounded-[2rem] border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `rounded-[1.75rem] border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-[2rem] ${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent-fill)] px-7 py-3 text-sm font-black uppercase tracking-[0.04em] text-[var(--slot4-on-accent)] transition duration-300 hover:scale-95 active:scale-90`,
    secondary: `inline-flex items-center justify-center gap-2 rounded-full border border-[var(--slot4-accent)] bg-transparent px-7 py-3 text-sm font-black uppercase tracking-[0.04em] text-[var(--slot4-accent)] transition duration-300 hover:scale-95 hover:bg-[var(--slot4-accent)] hover:text-[var(--slot4-on-accent)] active:scale-90`,
    accent: `inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-orange)] px-7 py-3 text-sm font-black uppercase tracking-[0.04em] text-white transition duration-300 hover:scale-95 active:scale-90`,
  },
  media: {
    frame: `relative overflow-hidden rounded-xl ${editablePalette.mediaBg}`,
    ratio: 'aspect-[2/3]',
  },
  motion: {
    lift: 'transition duration-300 hover:-translate-y-1 hover:scale-[0.99] hover:shadow-[0_18px_0_rgba(255,3,0,0.08)]',
    fade: 'transition duration-300 hover:opacity-80',
  },
} as const

export const aiLayoutRules = [
  'Change the full site color palette in editableRootStyle first; all homepage sections consume those CSS variables.',
  'Keep page structure in src/editable/sections/HomeSections.tsx so AI can redesign the whole home experience in one file.',
  'Use wide readable grids; never create skinny columns for paragraphs or cards.',
  'Use chunky horizontal rails and rounded snack-pack cards, matching the Snaxxco reference rhythm.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
